# -*- coding: utf-8 -*-
"""E M detection using speech and text Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZzuvBTjJKVRrMbYFrhpH7GR3oIfx8kqV
"""

# ── Install everything needed ────────────────────────────────
!pip install -q librosa soundfile vaderSentiment transformers datasets
!pip install -q textblob tensorflow-datasets gdown
!pip install -q huggingface_hub

import nltk
nltk.download('vader_lexicon', quiet=True)
nltk.download('stopwords',     quiet=True)
nltk.download('punkt',         quiet=True)
nltk.download('punkt_tab',     quiet=True)
nltk.download('wordnet',       quiet=True)
print("✅ All packages installed successfully.")

# ── Core imports ────────────────────────────────────────────
import os, re, string, warnings, zipfile, urllib.request
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
warnings.filterwarnings('ignore')

# Audio
import librosa
import librosa.display
from IPython.display import Audio, display

# Sklearn
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

# Keras / TF
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (Conv1D, Conv2D, MaxPooling1D, MaxPooling2D,
    Dense, Dropout, Flatten, BatchNormalization)
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping, ModelCheckpoint
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# NLP
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from textblob import TextBlob
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

print(f"✅ TensorFlow {tf.__version__} | GPU: {tf.config.list_physical_devices('GPU')}")

# ── Download RAVDESS from HuggingFace Hub ───────────────────
from huggingface_hub import snapshot_download
import shutil

RAVDESS_DIR = '/content/ravdess_audio'

if not os.path.exists(RAVDESS_DIR) or len(os.listdir(RAVDESS_DIR)) == 0:
    print("⬇️  Downloading RAVDESS dataset from HuggingFace (~400MB) ...")
    try:
        local_dir = snapshot_download(
            repo_id="cahya/ravdess",
            repo_type="dataset",
            local_dir=RAVDESS_DIR,
            ignore_patterns=["*.git*","*.md","*video*"]
        )
        print(f"✅ RAVDESS downloaded to {RAVDESS_DIR}")
    except Exception as e:
        print(f"HuggingFace download failed ({e}), trying alternative...")
        # Alternative: download a curated small subset via gdown
        # Google Drive public link for RAVDESS audio-only (speech actors 01-05, ~80MB)
        os.makedirs(RAVDESS_DIR, exist_ok=True)
        import gdown
        # Public RAVDESS audio subset shared file
        url = "https://zenodo.org/record/1188976/files/Audio_Speech_Actors_01-24.zip"
        zip_path = "/content/ravdess.zip"
        print("Downloading from Zenodo (~215MB)...")
        urllib.request.urlretrieve(url, zip_path)
        with zipfile.ZipFile(zip_path, 'r') as z:
            z.extractall(RAVDESS_DIR)
        os.remove(zip_path)
        print("✅ RAVDESS extracted.")
else:
    print(f"✅ RAVDESS already present at {RAVDESS_DIR}")

# ── List what we got ─────────────────────────────────────────
all_wav = []
for root, dirs, files in os.walk(RAVDESS_DIR):
    for f in files:
        if f.endswith('.wav'):
            all_wav.append(os.path.join(root, f))
print(f"Found {len(all_wav)} .wav files.")

# ── RAVDESS filename format: 03-01-05-01-02-01-12.wav ────────
# Position 2 (index) = emotion code
emotion_map = {
    '01':'neutral','02':'calm','03':'happy','04':'sad',
    '05':'angry','06':'fear','07':'disgust','08':'surprise'
}

paths, emotions = [], []
for wav in all_wav:
    fname = os.path.basename(wav)
    parts = fname.replace('.wav','').split('-')
    if len(parts) >= 3:
        code = parts[2]
        if code in emotion_map:
            paths.append(wav)
            emotions.append(emotion_map[code])

data_path = pd.DataFrame({'Path': paths, 'Emotion': emotions})
data_path.to_csv('/content/audio_metadata.csv', index=False)
print(f"✅ DataFrame built: {len(data_path)} files")
print(data_path['Emotion'].value_counts())

plt.figure(figsize=(10, 4))
sns.countplot(x='Emotion', data=data_path, palette='Set2',
              order=data_path['Emotion'].value_counts().index)
plt.title('RAVDESS — Emotion Distribution', fontsize=14)
plt.xlabel('Emotion'); plt.ylabel('Count')
plt.xticks(rotation=30); plt.tight_layout(); plt.show()

# ── Augmentation helpers ─────────────────────────────────────
def add_noise(data, factor=0.035):
    return data + factor * np.random.uniform() * np.amax(data) * np.random.normal(size=data.shape[0])

def time_stretch(data, rate=0.8):
    return librosa.effects.time_stretch(data, rate=rate)

def pitch_shift_audio(data, sr, factor=0.7):
    return librosa.effects.pitch_shift(data, sr=sr, n_steps=factor)

# ── Feature extractor: ZCR + Chroma + MFCC + RMS + MelSpec ──
def extract_features(data, sr=22050):
    result = np.array([])
    zcr    = np.mean(librosa.feature.zero_crossing_rate(y=data).T, axis=0)
    result = np.hstack((result, zcr))
    stft   = np.abs(librosa.stft(data))
    chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sr).T, axis=0)
    result = np.hstack((result, chroma))
    mfcc   = np.mean(librosa.feature.mfcc(y=data, sr=sr, n_mfcc=20).T, axis=0)
    result = np.hstack((result, mfcc))
    rms    = np.mean(librosa.feature.rms(y=data).T, axis=0)
    result = np.hstack((result, rms))
    mel    = np.mean(librosa.feature.melspectrogram(y=data, sr=sr).T, axis=0)
    result = np.hstack((result, mel))
    return result

def get_features(path):
    data, sr = librosa.load(path, duration=2.5, offset=0.6)
    feats = []
    feats.append(extract_features(data, sr))
    feats.append(extract_features(add_noise(data)))
    feats.append(extract_features(time_stretch(data)))
    feats.append(extract_features(pitch_shift_audio(data, sr)))
    return feats

print("✅ Augmentation & feature extraction functions ready.")

# ── Visualise waveform & spectrogram for each emotion ────────
sample_emotions = data_path['Emotion'].unique()[:4]
fig, axes = plt.subplots(len(sample_emotions), 2, figsize=(14, 3*len(sample_emotions)))

for i, em in enumerate(sample_emotions):
    sample_path = data_path[data_path['Emotion']==em]['Path'].values[0]
    data_audio, sr = librosa.load(sample_path, duration=2.5)

    # Waveform
    librosa.display.waveshow(data_audio, sr=sr, ax=axes[i][0])
    axes[i][0].set_title(f'Waveform — {em}')

    # Spectrogram
    X = librosa.stft(data_audio)
    Xdb = librosa.amplitude_to_db(np.abs(X))
    librosa.display.specshow(Xdb, sr=sr, x_axis='time', y_axis='hz', ax=axes[i][1])
    axes[i][1].set_title(f'Spectrogram — {em}')

plt.tight_layout(); plt.show()

# ── Extract features (cached) ────────────────────────────────
if os.path.exists('/content/ser_features.csv'):
    Features = pd.read_csv('/content/ser_features.csv')
    print("✅ Loaded cached features:", Features.shape)
else:
    print(f"Extracting features from {len(data_path)} files (with 4x augmentation)...")
    X_all, Y_all = [], []
    for i, (path, emotion) in enumerate(zip(data_path.Path, data_path.Emotion)):
        try:
            for feat in get_features(path):
                X_all.append(feat)
                Y_all.append(emotion)
        except Exception:
            pass
        if (i+1) % 100 == 0:
            print(f"  {i+1}/{len(data_path)} done...")

    Features = pd.DataFrame(X_all)
    Features['label'] = Y_all
    Features.to_csv('/content/ser_features.csv', index=False)
    print("✅ Done! Features shape:", Features.shape)

# ── Prepare training data ────────────────────────────────────
X = Features.iloc[:, :-1].values
Y = Features['label'].values

encoder_ser = OneHotEncoder(sparse_output=False)
Y_enc = encoder_ser.fit_transform(Y.reshape(-1,1))

x_train, x_test, y_train, y_test = train_test_split(
    X, Y_enc, test_size=0.2, random_state=42, shuffle=True)

scaler_ser = StandardScaler()
x_train = scaler_ser.fit_transform(x_train)
x_test  = scaler_ser.transform(x_test)
x_train = np.expand_dims(x_train, axis=2)
x_test  = np.expand_dims(x_test,  axis=2)

print(f"Train: {x_train.shape} | Test: {x_test.shape} | Classes: {y_train.shape[1]}")

# ── Build Conv1D model ───────────────────────────────────────
n_classes_ser = y_train.shape[1]

ser_model = Sequential([
    Conv1D(256, 5, padding='same', activation='relu', input_shape=(x_train.shape[1], 1)),
    BatchNormalization(), MaxPooling1D(pool_size=5, strides=2, padding='same'),

    Conv1D(128, 5, padding='same', activation='relu'),
    BatchNormalization(), MaxPooling1D(pool_size=5, strides=2, padding='same'),

    Conv1D(64, 5, padding='same', activation='relu'),
    BatchNormalization(), MaxPooling1D(pool_size=5, strides=2, padding='same'),
    Dropout(0.3),

    Flatten(),
    Dense(128, activation='relu'), Dropout(0.3),
    Dense(64,  activation='relu'), Dropout(0.2),
    Dense(n_classes_ser, activation='softmax')
])
ser_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
ser_model.summary()

# ── Train ────────────────────────────────────────────────────
callbacks_ser = [
    ReduceLROnPlateau(monitor='val_loss', factor=0.4, patience=3, min_lr=1e-7, verbose=1),
    EarlyStopping(monitor='val_accuracy', patience=8, restore_best_weights=True, verbose=1),
    ModelCheckpoint('/content/ser_model_best.h5', save_best_only=True, verbose=0)
]

history_ser = ser_model.fit(
    x_train, y_train, batch_size=64, epochs=50,
    validation_data=(x_test, y_test), callbacks=callbacks_ser
)

# ── Plot results ─────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 5))
axes[0].plot(history_ser.history['loss'],     label='Train Loss')
axes[0].plot(history_ser.history['val_loss'], label='Val Loss')
axes[0].set_title('SER — Loss'); axes[0].legend()
axes[1].plot(history_ser.history['accuracy'],     label='Train Acc')
axes[1].plot(history_ser.history['val_accuracy'], label='Val Acc')
axes[1].set_title('SER — Accuracy'); axes[1].legend()
plt.tight_layout(); plt.show()

test_loss, test_acc = ser_model.evaluate(x_test, y_test, verbose=0)
print(f"\n✅ SER Test Accuracy: {test_acc*100:.2f}%")

# ── Confusion Matrix ─────────────────────────────────────────
pred_test   = ser_model.predict(x_test, verbose=0)
y_pred_ser  = encoder_ser.inverse_transform(pred_test).flatten()
y_true_ser  = encoder_ser.inverse_transform(y_test).flatten()

cm = confusion_matrix(y_true_ser, y_pred_ser)
labels = encoder_ser.categories_[0]
plt.figure(figsize=(10, 8))
sns.heatmap(pd.DataFrame(cm, index=labels, columns=labels),
            annot=True, fmt='d', cmap='Blues', linewidths=0.5)
plt.title('SER — Confusion Matrix', fontsize=14)
plt.xlabel('Predicted'); plt.ylabel('Actual')
plt.tight_layout(); plt.show()

print(classification_report(y_true_ser, y_pred_ser))

# ── Predict from any audio file ─────────────────────────────
def predict_speech_emotion(audio_path):
    data, sr = librosa.load(audio_path, duration=2.5, offset=0.6)
    feat = extract_features(data, sr).reshape(1, -1)
    feat = scaler_ser.transform(feat)
    feat = np.expand_dims(feat, axis=2)
    pred = ser_model.predict(feat, verbose=0)
    label = encoder_ser.inverse_transform(pred)[0][0]
    conf  = np.max(pred) * 100

    plt.figure(figsize=(10, 3))
    librosa.display.waveshow(data, sr=sr)
    plt.title(f"🎤 Predicted Emotion: {label.upper()} ({conf:.1f}%)")
    plt.tight_layout(); plt.show()

    print(f"\n🎤 Speech Emotion: {label.upper()} | Confidence: {conf:.1f}%")
    return label

# ── Test on a sample from the dataset ───────────────────────
sample_wav = data_path['Path'].iloc[0]
predict_speech_emotion(sample_wav)

# ── Load Twitter Emotion dataset from HuggingFace ────────────
from datasets import load_dataset

print("⬇️  Loading Twitter Emotion dataset from HuggingFace Hub...")
emotion_dataset = load_dataset("dair-ai/emotion", trust_remote_code=True)

TWITTER_LABELS = emotion_dataset['train'].features['label'].names
print(f"✅ Dataset loaded! Labels: {TWITTER_LABELS}")
print(f"Train: {len(emotion_dataset['train'])} | Val: {len(emotion_dataset['validation'])} | Test: {len(emotion_dataset['test'])}")

# Preview
df_twitter = pd.DataFrame(emotion_dataset['train'])
df_twitter['emotion'] = df_twitter['label'].map(dict(enumerate(TWITTER_LABELS)))
df_twitter.head(8)

# ── Visualise label distribution ─────────────────────────────
plt.figure(figsize=(9, 4))
vc = df_twitter['emotion'].value_counts()
sns.barplot(x=vc.values, y=vc.index, palette='Set2')
plt.title('Twitter Emotion Dataset — Distribution', fontsize=14)
plt.xlabel('Count'); plt.tight_layout(); plt.show()

# ── Full preprocessing pipeline from reference notebooks ─────
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = str(text).lower()                                    # 1. Lowercase
    text = re.sub(r'<.*?>', '', text)                           # 2. Remove HTML
    text = re.sub(r'https?://\S+|www\.\S+', '', text)       # 3. Remove URLs
    text = text.translate(str.maketrans('', '', string.punctuation))  # 4. Remove punctuation
    text = re.sub(r'\d+', '', text)                            # 5. Remove numbers
    text = re.sub(r'\s+', ' ', text).strip()                  # 6. Normalise whitespace
    tokens = word_tokenize(text)                                 # 7. Tokenise
    tokens = [lemmatizer.lemmatize(t) for t in tokens          # 8. Lemmatise + remove stopwords
              if t not in stop_words and len(t) > 2]
    return ' '.join(tokens)

# Apply to dataset
df_twitter['cleaned'] = df_twitter['text'].apply(clean_text)
print("=== Preprocessing Demo (first 3 rows) ===")
for _, row in df_twitter.head(3).iterrows():
    print(f"Original : {row['text']}")
    print(f"Cleaned  : {row['cleaned']}")
    print(f"Emotion  : {row['emotion']}\n")

vader_analyzer = SentimentIntensityAnalyzer()

def full_text_analysis(text):
    """VADER + TextBlob combined analysis."""
    cleaned  = clean_text(text)
    # VADER
    scores   = vader_analyzer.polarity_scores(cleaned)
    compound = scores['compound']
    if compound >= 0.05:   vader_sentiment = 'Positive 😊'
    elif compound <= -0.05: vader_sentiment = 'Negative 😠'
    else:                  vader_sentiment = 'Neutral 😐'

    # TextBlob
    blob = TextBlob(cleaned)
    tb_polarity = blob.sentiment.polarity
    if tb_polarity > 0.1:   tb_sentiment = 'Positive 😊'
    elif tb_polarity < -0.1: tb_sentiment = 'Negative 😔'
    else:                   tb_sentiment = 'Neutral 😐'

    # Keyword-based emotion
    kw_map = {
        'joy':      ['happy','joy','love','great','wonderful','excited','glad'],
        'anger':    ['angry','furious','hate','rage','mad','annoyed','terrible'],
        'sadness':  ['sad','cry','unhappy','depressed','miss','lonely','grief'],
        'fear':     ['fear','scared','afraid','terror','anxious','worry'],
        'surprise': ['surprised','shocked','wow','unbelievable','amazed'],
        'love':     ['love','adore','cherish','affection','caring','devoted']
    }
    kw_tokens = set(cleaned.split())
    kw_scores = {e: len(kw_tokens & set(ws)) for e, ws in kw_map.items()}
    kw_emotion = max(kw_scores, key=kw_scores.get) if max(kw_scores.values()) > 0 else 'neutral'

    return {
        'text': text, 'cleaned': cleaned,
        'vader_sentiment': vader_sentiment, 'vader_compound': round(compound, 4),
        'tb_sentiment': tb_sentiment, 'tb_polarity': round(tb_polarity, 4),
        'tb_subjectivity': round(blob.sentiment.subjectivity, 4),
        'keyword_emotion': kw_emotion
    }

# ── Test on Twitter dataset samples ──────────────────────────
print("=== Sentiment Analysis on Twitter Emotion Dataset ===\n")
for _, row in df_twitter.sample(5, random_state=42).iterrows():
    r = full_text_analysis(row['text'])
    print(f"Text          : {r['text'][:70]}")
    print(f"True Emotion  : {row['emotion'].upper()}")
    print(f"VADER         : {r['vader_sentiment']} (compound={r['vader_compound']})")
    print(f"TextBlob      : {r['tb_sentiment']} (pol={r['tb_polarity']})")
    print(f"Keyword Emotion: {r['keyword_emotion'].upper()}\n")

from transformers import pipeline as hf_pipeline

print("⬇️  Loading emotion transformer (distilroberta, ~130MB, first run only)...")
emotion_pipe = hf_pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    top_k=None, device=-1   # set device=0 to use GPU
)
print("✅ Transformer model loaded!")

def predict_emotion_transformer(text, show_bar=True):
    """Predict emotion probabilities using DistilRoBERTa."""
    results = sorted(emotion_pipe(text[:512])[0], key=lambda x: x['score'], reverse=True)
    top = results[0]

    if show_bar:
        labels = [r['label'] for r in results]
        scores = [r['score'] for r in results]
        colors = plt.cm.Set2(np.linspace(0, 1, len(labels)))
        plt.figure(figsize=(8, 3))
        bars = plt.barh(labels, scores, color=colors)
        plt.xlim(0, 1); plt.xlabel('Probability')
        plt.title(f'Transformer Emotion: "{text[:50]}..."')
        for bar, sc in zip(bars, scores):
            plt.text(sc + 0.01, bar.get_y() + bar.get_height()/2,
                     f'{sc*100:.1f}%', va='center', fontsize=9)
        plt.tight_layout(); plt.show()

    print(f"🏆 Top emotion: {top['label'].upper()} ({top['score']*100:.1f}%)")
    return top['label'], top['score']

# ── Test on Twitter samples ───────────────────────────────────
print("=== Transformer Predictions on Twitter Dataset ===\n")
for _, row in df_twitter.sample(4, random_state=7).iterrows():
    print(f"Text: {row['text'][:80]}")
    print(f"True: {row['emotion'].upper()}")
    predict_emotion_transformer(row['text'])
    print()

# ── Run full VADER analysis on test set ──────────────────────
print("Running batch analysis on 500 test samples...")
df_test = pd.DataFrame(emotion_dataset['test']).head(500)
df_test['emotion_name'] = df_test['label'].map(dict(enumerate(TWITTER_LABELS)))

results_list = [full_text_analysis(t) for t in df_test['text']]
df_results = pd.DataFrame(results_list)
df_results['true_emotion'] = df_test['emotion_name'].values

# ── Dashboard ────────────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1. True vs Keyword emotion heatmap
ct = pd.crosstab(df_results['true_emotion'], df_results['keyword_emotion'])
sns.heatmap(ct, annot=True, fmt='d', cmap='YlOrRd', ax=axes[0][0])
axes[0][0].set_title('True Emotion vs Keyword Prediction', fontsize=12)

# 2. VADER compound distribution per emotion
for em in df_results['true_emotion'].unique():
    subset = df_results[df_results['true_emotion']==em]['vader_compound']
    axes[0][1].hist(subset, alpha=0.5, label=em, bins=20)
axes[0][1].set_title('VADER Compound Score Distribution by Emotion')
axes[0][1].legend(fontsize=8); axes[0][1].set_xlabel('Compound Score')

# 3. Sentiment distribution pie
vc_sent = df_results['vader_sentiment'].value_counts()
axes[1][0].pie(vc_sent, labels=vc_sent.index, autopct='%1.1f%%',
               colors=['#66bb6a','#ef5350','#90a4ae'])
axes[1][0].set_title('VADER Sentiment Distribution')

# 4. TextBlob polarity vs subjectivity
colors_map = {'Positive 😊':'#66bb6a','Negative 😔':'#ef5350','Neutral 😐':'#90a4ae'}
for sent, col in colors_map.items():
    mask = df_results['tb_sentiment'] == sent
    axes[1][1].scatter(df_results[mask]['tb_polarity'],
                       df_results[mask]['tb_subjectivity'],
                       c=col, alpha=0.5, label=sent, s=20)
axes[1][1].set_xlabel('Polarity'); axes[1][1].set_ylabel('Subjectivity')
axes[1][1].set_title('TextBlob: Polarity vs Subjectivity')
axes[1][1].axvline(0, color='gray', ls='--'); axes[1][1].legend()

plt.suptitle('NLP Sentiment & Emotion — Analysis Dashboard', fontsize=15, y=1.01)
plt.tight_layout(); plt.show()
print(f"✅ Batch analysis complete on {len(df_results)} samples.")

def multimodal_emotion_report(text_input=None, audio_path=None, image_path=None):
    """
    Unified emotion detection across all three modalities.
    Pass any combination of text, audio path, or image path.
    """
    print("=" * 65)
    print("🧠  MULTIMODAL EMOTION DETECTION — UNIFIED REPORT")
    print("=" * 65)
    results = {}

    # ── 📝 TEXT ───────────────────────────────────────────────
    if text_input:
        print("\n📝 TEXT ANALYSIS")
        print("─" * 40)
        r = full_text_analysis(text_input)
        print(f"  Input     : {text_input[:70]}")
        print(f"  Cleaned   : {r['cleaned'][:70]}")
        print(f"  VADER     : {r['vader_sentiment']}  (compound={r['vader_compound']})")
        print(f"  TextBlob  : {r['tb_sentiment']}  (pol={r['tb_polarity']}, subj={r['tb_subjectivity']})")
        try:
            em, sc = predict_emotion_transformer(text_input, show_bar=True)
            print(f"  Transformer: {em.upper()} ({sc*100:.1f}%)")
            results['text_emotion'] = em
        except:
            results['text_emotion'] = r['keyword_emotion']
        results['text_sentiment'] = r['vader_sentiment']

    # ── 🎤 SPEECH ─────────────────────────────────────────────
    if audio_path and os.path.exists(audio_path):
        print("\n🎤 SPEECH ANALYSIS")
        print("─" * 40)
        label = predict_speech_emotion(audio_path)
        results['speech_emotion'] = label
    elif audio_path:
        print(f"\n🎤 Audio not found: {audio_path}")

    # ── 😊 FACE ───────────────────────────────────────────────
    if image_path and os.path.exists(image_path):
        print("\n😊 FACIAL ANALYSIS")
        print("─" * 40)
        predict_face_emotion(image_path)
    else:
        print("\n😊 FACIAL: Call webcam_emotion_predict() for live detection.")

    # ── Summary ───────────────────────────────────────────────
    print("\n" + "=" * 65)
    print("📊  FINAL SUMMARY")
    for k, v in results.items():
        print(f"  {k:20s}: {str(v).upper()}")
    print("=" * 65)
    return results

# ── DEMO RUN ──────────────────────────────────────────────────
demo = multimodal_emotion_report(
    text_input="I am so happy and excited about this amazing project! It turned out wonderful.",
    audio_path=data_path['Path'].iloc[0] if len(data_path) > 0 else None,
    image_path=None
)